<?xml version="1.0" encoding="utf-8"?><Database Name="UROLOJI" Class="UROLOJIDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=UROLOJI;Persist Security Info=True;User ID=sa" SettingsObjectName="UROLOJI.Properties.Settings" SettingsPropertyName="UROLOJIConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tblTakipVerileri" Member="tblTakipVerileris">
    <Type Name="tblTakipVerileri">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="hastaID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="hastaNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Postop3AyLokalNüks" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Postop3AyKreatin" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Postop6AyLokalNüks" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Postop6AyKreatin" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Postop12AyLokalNüks" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Postop12AyKreatin" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="tblHastaBilgileri_tblTakipVerileri" Member="tblHastaBilgileri" ThisKey="hastaID" OtherKey="hastaID" Type="tblHastaBilgileri" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblPosOperatifOzellikler" Member="tblPosOperatifOzelliklers">
    <Type Name="tblPosOperatifOzellikler">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="hastaID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="hastaNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PeropVeErkenKomp" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Dren" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PostopAnaliz" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Sonda" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="HospSuresi" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PreopKreatin" Type="System.Decimal" DbType="Decimal(6,0)" CanBeNull="true" />
      <Column Name="PostopKreatin" Type="System.Decimal" DbType="Decimal(6,0)" CanBeNull="true" />
      <Column Name="PreopHct" Type="System.Decimal" DbType="Decimal(6,0)" CanBeNull="true" />
      <Column Name="PostopHct" Type="System.Decimal" DbType="Decimal(6,0)" CanBeNull="true" />
      <Column Name="PreopHb" Type="System.Decimal" DbType="Decimal(6,0)" CanBeNull="true" />
      <Column Name="PostopHb" Type="System.Decimal" DbType="Decimal(6,0)" CanBeNull="true" />
      <Column Name="Takip" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Tel" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PostopGecKomp" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="KompClavien" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Association Name="tblHastaBilgileri_tblPosOperatifOzellikler" Member="tblHastaBilgileri" ThisKey="hastaID" OtherKey="hastaID" Type="tblHastaBilgileri" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblPatolojikVeriler" Member="tblPatolojikVerilers">
    <Type Name="tblPatolojikVeriler">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="hastaID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="hastaNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Patoloji" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="AltGrup" Type="System.String" DbType="NVarChar(70)" CanBeNull="true" />
      <Column Name="FurhmanGrade" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PatolojikEvre" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="CerrahiSinir" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Association Name="tblHastaBilgileri_tblPatolojikVeriler" Member="tblHastaBilgileri" ThisKey="hastaID" OtherKey="hastaID" Type="tblHastaBilgileri" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblOpTuru" Member="tblOpTurus">
    <Type Name="tblOpTuru">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OpTuru" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblOperatifOzellikler" Member="tblOperatifOzelliklers">
    <Type Name="tblOperatifOzellikler">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="hastaID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HastaNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PksAciklama" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Sik" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="CoOperasyon" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Iskemi" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PortSayisi" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="YardımYnt" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Sure" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Dren" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Kanama" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Piyes" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="tblHastaBilgileri_tblOperatifOzellikler" Member="tblHastaBilgileri" ThisKey="hastaID" OtherKey="hastaID" Type="tblHastaBilgileri" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblKoMorbidite" Member="tblKoMorbidites">
    <Type Name="tblKoMorbidite">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="KoMorbidite" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblDR" Member="tblDRs">
    <Type Name="tblDR">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DR" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblHastaBilgileri" Member="tblHastaBilgileris">
    <Type Name="tblHastaBilgileri">
      <Column Name="hastaID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HastaNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Ad" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Soyad" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Protokol" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="OpTarihi" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="OpTuru" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Takip" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Anah" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="tblHastaBilgileri_tblTakipVerileri" Member="tblTakipVerileris" ThisKey="hastaID" OtherKey="hastaID" Type="tblTakipVerileri" />
      <Association Name="tblHastaBilgileri_tblPosOperatifOzellikler" Member="tblPosOperatifOzelliklers" ThisKey="hastaID" OtherKey="hastaID" Type="tblPosOperatifOzellikler" />
      <Association Name="tblHastaBilgileri_tblPatolojikVeriler" Member="tblPatolojikVerilers" ThisKey="hastaID" OtherKey="hastaID" Type="tblPatolojikVeriler" />
      <Association Name="tblHastaBilgileri_tblOperatifOzellikler" Member="tblOperatifOzelliklers" ThisKey="hastaID" OtherKey="hastaID" Type="tblOperatifOzellikler" />
      <Association Name="tblHastaBilgileri_tblDemografikOzellikler" Member="tblDemografikOzelliklers" ThisKey="hastaID" OtherKey="hastaID" Type="tblDemografikOzellikler" />
    </Type>
  </Table>
  <Table Name="dbo.tblDemografikOzellikler" Member="tblDemografikOzelliklers">
    <Type Name="tblDemografikOzellikler">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="hastaID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HastaNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Yas" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Boy" Type="System.Decimal" DbType="Decimal(5,2)" CanBeNull="true" />
      <Column Name="Kilo" Type="System.Decimal" DbType="Decimal(5,2)" CanBeNull="true" />
      <Column Name="Bmi" Type="System.Decimal" DbType="Decimal(5,2)" CanBeNull="true" />
      <Column Name="Asa" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Dr" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Cins" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Taraf" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Lokalizasyon" Type="System.String" DbType="NVarChar(70)" CanBeNull="true" />
      <Column Name="Boyut" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[Ko-Morbidite]" Member="Ko_Morbidite" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Association Name="tblHastaBilgileri_tblDemografikOzellikler" Member="tblHastaBilgileri" ThisKey="hastaID" OtherKey="hastaID" Type="tblHastaBilgileri" IsForeignKey="true" />
    </Type>
  </Table>
</Database>