#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UROLOJI.Modal
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="UROLOJI")]
	public partial class UROLOJIDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttblTakipVerileri(tblTakipVerileri instance);
    partial void UpdatetblTakipVerileri(tblTakipVerileri instance);
    partial void DeletetblTakipVerileri(tblTakipVerileri instance);
    partial void InserttblPosOperatifOzellikler(tblPosOperatifOzellikler instance);
    partial void UpdatetblPosOperatifOzellikler(tblPosOperatifOzellikler instance);
    partial void DeletetblPosOperatifOzellikler(tblPosOperatifOzellikler instance);
    partial void InserttblPatolojikVeriler(tblPatolojikVeriler instance);
    partial void UpdatetblPatolojikVeriler(tblPatolojikVeriler instance);
    partial void DeletetblPatolojikVeriler(tblPatolojikVeriler instance);
    partial void InserttblOpTuru(tblOpTuru instance);
    partial void UpdatetblOpTuru(tblOpTuru instance);
    partial void DeletetblOpTuru(tblOpTuru instance);
    partial void InserttblOperatifOzellikler(tblOperatifOzellikler instance);
    partial void UpdatetblOperatifOzellikler(tblOperatifOzellikler instance);
    partial void DeletetblOperatifOzellikler(tblOperatifOzellikler instance);
    partial void InserttblKoMorbidite(tblKoMorbidite instance);
    partial void UpdatetblKoMorbidite(tblKoMorbidite instance);
    partial void DeletetblKoMorbidite(tblKoMorbidite instance);
    partial void InserttblDR(tblDR instance);
    partial void UpdatetblDR(tblDR instance);
    partial void DeletetblDR(tblDR instance);
    partial void InserttblHastaBilgileri(tblHastaBilgileri instance);
    partial void UpdatetblHastaBilgileri(tblHastaBilgileri instance);
    partial void DeletetblHastaBilgileri(tblHastaBilgileri instance);
    partial void InserttblDemografikOzellikler(tblDemografikOzellikler instance);
    partial void UpdatetblDemografikOzellikler(tblDemografikOzellikler instance);
    partial void DeletetblDemografikOzellikler(tblDemografikOzellikler instance);
    #endregion
		
		public UROLOJIDBDataContext() : 
				base(global::UROLOJI.Properties.Settings.Default.UROLOJIConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public UROLOJIDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public UROLOJIDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public UROLOJIDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public UROLOJIDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tblTakipVerileri> tblTakipVerileris
		{
			get
			{
				return this.GetTable<tblTakipVerileri>();
			}
		}
		
		public System.Data.Linq.Table<tblPosOperatifOzellikler> tblPosOperatifOzelliklers
		{
			get
			{
				return this.GetTable<tblPosOperatifOzellikler>();
			}
		}
		
		public System.Data.Linq.Table<tblPatolojikVeriler> tblPatolojikVerilers
		{
			get
			{
				return this.GetTable<tblPatolojikVeriler>();
			}
		}
		
		public System.Data.Linq.Table<tblOpTuru> tblOpTurus
		{
			get
			{
				return this.GetTable<tblOpTuru>();
			}
		}
		
		public System.Data.Linq.Table<tblOperatifOzellikler> tblOperatifOzelliklers
		{
			get
			{
				return this.GetTable<tblOperatifOzellikler>();
			}
		}
		
		public System.Data.Linq.Table<tblKoMorbidite> tblKoMorbidites
		{
			get
			{
				return this.GetTable<tblKoMorbidite>();
			}
		}
		
		public System.Data.Linq.Table<tblDR> tblDRs
		{
			get
			{
				return this.GetTable<tblDR>();
			}
		}
		
		public System.Data.Linq.Table<tblHastaBilgileri> tblHastaBilgileris
		{
			get
			{
				return this.GetTable<tblHastaBilgileri>();
			}
		}
		
		public System.Data.Linq.Table<tblDemografikOzellikler> tblDemografikOzelliklers
		{
			get
			{
				return this.GetTable<tblDemografikOzellikler>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblTakipVerileri")]
	public partial class tblTakipVerileri : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _hastaID;
		
		private System.Nullable<int> _hastaNo;
		
		private string _Postop3AyLokalNüks;
		
		private string _Postop3AyKreatin;
		
		private string _Postop6AyLokalNüks;
		
		private string _Postop6AyKreatin;
		
		private string _Postop12AyLokalNüks;
		
		private string _Postop12AyKreatin;
		
		private EntityRef<tblHastaBilgileri> _tblHastaBilgileri;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnhastaIDChanging(System.Nullable<int> value);
    partial void OnhastaIDChanged();
    partial void OnhastaNoChanging(System.Nullable<int> value);
    partial void OnhastaNoChanged();
    partial void OnPostop3AyLokalNüksChanging(string value);
    partial void OnPostop3AyLokalNüksChanged();
    partial void OnPostop3AyKreatinChanging(string value);
    partial void OnPostop3AyKreatinChanged();
    partial void OnPostop6AyLokalNüksChanging(string value);
    partial void OnPostop6AyLokalNüksChanged();
    partial void OnPostop6AyKreatinChanging(string value);
    partial void OnPostop6AyKreatinChanged();
    partial void OnPostop12AyLokalNüksChanging(string value);
    partial void OnPostop12AyLokalNüksChanged();
    partial void OnPostop12AyKreatinChanging(string value);
    partial void OnPostop12AyKreatinChanged();
    #endregion
		
		public tblTakipVerileri()
		{
			this._tblHastaBilgileri = default(EntityRef<tblHastaBilgileri>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hastaID", DbType="Int")]
		public System.Nullable<int> hastaID
		{
			get
			{
				return this._hastaID;
			}
			set
			{
				if ((this._hastaID != value))
				{
					if (this._tblHastaBilgileri.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnhastaIDChanging(value);
					this.SendPropertyChanging();
					this._hastaID = value;
					this.SendPropertyChanged("hastaID");
					this.OnhastaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hastaNo", DbType="Int")]
		public System.Nullable<int> hastaNo
		{
			get
			{
				return this._hastaNo;
			}
			set
			{
				if ((this._hastaNo != value))
				{
					this.OnhastaNoChanging(value);
					this.SendPropertyChanging();
					this._hastaNo = value;
					this.SendPropertyChanged("hastaNo");
					this.OnhastaNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Postop3AyLokalNüks", DbType="NVarChar(50)")]
		public string Postop3AyLokalNüks
		{
			get
			{
				return this._Postop3AyLokalNüks;
			}
			set
			{
				if ((this._Postop3AyLokalNüks != value))
				{
					this.OnPostop3AyLokalNüksChanging(value);
					this.SendPropertyChanging();
					this._Postop3AyLokalNüks = value;
					this.SendPropertyChanged("Postop3AyLokalNüks");
					this.OnPostop3AyLokalNüksChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Postop3AyKreatin", DbType="NVarChar(50)")]
		public string Postop3AyKreatin
		{
			get
			{
				return this._Postop3AyKreatin;
			}
			set
			{
				if ((this._Postop3AyKreatin != value))
				{
					this.OnPostop3AyKreatinChanging(value);
					this.SendPropertyChanging();
					this._Postop3AyKreatin = value;
					this.SendPropertyChanged("Postop3AyKreatin");
					this.OnPostop3AyKreatinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Postop6AyLokalNüks", DbType="NVarChar(50)")]
		public string Postop6AyLokalNüks
		{
			get
			{
				return this._Postop6AyLokalNüks;
			}
			set
			{
				if ((this._Postop6AyLokalNüks != value))
				{
					this.OnPostop6AyLokalNüksChanging(value);
					this.SendPropertyChanging();
					this._Postop6AyLokalNüks = value;
					this.SendPropertyChanged("Postop6AyLokalNüks");
					this.OnPostop6AyLokalNüksChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Postop6AyKreatin", DbType="NVarChar(50)")]
		public string Postop6AyKreatin
		{
			get
			{
				return this._Postop6AyKreatin;
			}
			set
			{
				if ((this._Postop6AyKreatin != value))
				{
					this.OnPostop6AyKreatinChanging(value);
					this.SendPropertyChanging();
					this._Postop6AyKreatin = value;
					this.SendPropertyChanged("Postop6AyKreatin");
					this.OnPostop6AyKreatinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Postop12AyLokalNüks", DbType="NVarChar(50)")]
		public string Postop12AyLokalNüks
		{
			get
			{
				return this._Postop12AyLokalNüks;
			}
			set
			{
				if ((this._Postop12AyLokalNüks != value))
				{
					this.OnPostop12AyLokalNüksChanging(value);
					this.SendPropertyChanging();
					this._Postop12AyLokalNüks = value;
					this.SendPropertyChanged("Postop12AyLokalNüks");
					this.OnPostop12AyLokalNüksChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Postop12AyKreatin", DbType="NVarChar(50)")]
		public string Postop12AyKreatin
		{
			get
			{
				return this._Postop12AyKreatin;
			}
			set
			{
				if ((this._Postop12AyKreatin != value))
				{
					this.OnPostop12AyKreatinChanging(value);
					this.SendPropertyChanging();
					this._Postop12AyKreatin = value;
					this.SendPropertyChanged("Postop12AyKreatin");
					this.OnPostop12AyKreatinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblHastaBilgileri_tblTakipVerileri", Storage="_tblHastaBilgileri", ThisKey="hastaID", OtherKey="hastaID", IsForeignKey=true)]
		public tblHastaBilgileri tblHastaBilgileri
		{
			get
			{
				return this._tblHastaBilgileri.Entity;
			}
			set
			{
				tblHastaBilgileri previousValue = this._tblHastaBilgileri.Entity;
				if (((previousValue != value) 
							|| (this._tblHastaBilgileri.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblHastaBilgileri.Entity = null;
						previousValue.tblTakipVerileris.Remove(this);
					}
					this._tblHastaBilgileri.Entity = value;
					if ((value != null))
					{
						value.tblTakipVerileris.Add(this);
						this._hastaID = value.hastaID;
					}
					else
					{
						this._hastaID = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblHastaBilgileri");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblPosOperatifOzellikler")]
	public partial class tblPosOperatifOzellikler : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _hastaID;
		
		private System.Nullable<int> _hastaNo;
		
		private string _PeropVeErkenKomp;
		
		private System.Nullable<int> _Dren;
		
		private string _PostopAnaliz;
		
		private string _Sonda;
		
		private System.Nullable<int> _HospSuresi;
		
		private System.Nullable<decimal> _PreopKreatin;
		
		private System.Nullable<decimal> _PostopKreatin;
		
		private System.Nullable<decimal> _PreopHct;
		
		private System.Nullable<decimal> _PostopHct;
		
		private System.Nullable<decimal> _PreopHb;
		
		private System.Nullable<decimal> _PostopHb;
		
		private string _Takip;
		
		private string _Tel;
		
		private string _PostopGecKomp;
		
		private string _KompClavien;
		
		private EntityRef<tblHastaBilgileri> _tblHastaBilgileri;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnhastaIDChanging(System.Nullable<int> value);
    partial void OnhastaIDChanged();
    partial void OnhastaNoChanging(System.Nullable<int> value);
    partial void OnhastaNoChanged();
    partial void OnPeropVeErkenKompChanging(string value);
    partial void OnPeropVeErkenKompChanged();
    partial void OnDrenChanging(System.Nullable<int> value);
    partial void OnDrenChanged();
    partial void OnPostopAnalizChanging(string value);
    partial void OnPostopAnalizChanged();
    partial void OnSondaChanging(string value);
    partial void OnSondaChanged();
    partial void OnHospSuresiChanging(System.Nullable<int> value);
    partial void OnHospSuresiChanged();
    partial void OnPreopKreatinChanging(System.Nullable<decimal> value);
    partial void OnPreopKreatinChanged();
    partial void OnPostopKreatinChanging(System.Nullable<decimal> value);
    partial void OnPostopKreatinChanged();
    partial void OnPreopHctChanging(System.Nullable<decimal> value);
    partial void OnPreopHctChanged();
    partial void OnPostopHctChanging(System.Nullable<decimal> value);
    partial void OnPostopHctChanged();
    partial void OnPreopHbChanging(System.Nullable<decimal> value);
    partial void OnPreopHbChanged();
    partial void OnPostopHbChanging(System.Nullable<decimal> value);
    partial void OnPostopHbChanged();
    partial void OnTakipChanging(string value);
    partial void OnTakipChanged();
    partial void OnTelChanging(string value);
    partial void OnTelChanged();
    partial void OnPostopGecKompChanging(string value);
    partial void OnPostopGecKompChanged();
    partial void OnKompClavienChanging(string value);
    partial void OnKompClavienChanged();
    #endregion
		
		public tblPosOperatifOzellikler()
		{
			this._tblHastaBilgileri = default(EntityRef<tblHastaBilgileri>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hastaID", DbType="Int")]
		public System.Nullable<int> hastaID
		{
			get
			{
				return this._hastaID;
			}
			set
			{
				if ((this._hastaID != value))
				{
					if (this._tblHastaBilgileri.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnhastaIDChanging(value);
					this.SendPropertyChanging();
					this._hastaID = value;
					this.SendPropertyChanged("hastaID");
					this.OnhastaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hastaNo", DbType="Int")]
		public System.Nullable<int> hastaNo
		{
			get
			{
				return this._hastaNo;
			}
			set
			{
				if ((this._hastaNo != value))
				{
					this.OnhastaNoChanging(value);
					this.SendPropertyChanging();
					this._hastaNo = value;
					this.SendPropertyChanged("hastaNo");
					this.OnhastaNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PeropVeErkenKomp", DbType="NVarChar(50)")]
		public string PeropVeErkenKomp
		{
			get
			{
				return this._PeropVeErkenKomp;
			}
			set
			{
				if ((this._PeropVeErkenKomp != value))
				{
					this.OnPeropVeErkenKompChanging(value);
					this.SendPropertyChanging();
					this._PeropVeErkenKomp = value;
					this.SendPropertyChanged("PeropVeErkenKomp");
					this.OnPeropVeErkenKompChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dren", DbType="Int")]
		public System.Nullable<int> Dren
		{
			get
			{
				return this._Dren;
			}
			set
			{
				if ((this._Dren != value))
				{
					this.OnDrenChanging(value);
					this.SendPropertyChanging();
					this._Dren = value;
					this.SendPropertyChanged("Dren");
					this.OnDrenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostopAnaliz", DbType="NVarChar(50)")]
		public string PostopAnaliz
		{
			get
			{
				return this._PostopAnaliz;
			}
			set
			{
				if ((this._PostopAnaliz != value))
				{
					this.OnPostopAnalizChanging(value);
					this.SendPropertyChanging();
					this._PostopAnaliz = value;
					this.SendPropertyChanged("PostopAnaliz");
					this.OnPostopAnalizChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sonda", DbType="NVarChar(50)")]
		public string Sonda
		{
			get
			{
				return this._Sonda;
			}
			set
			{
				if ((this._Sonda != value))
				{
					this.OnSondaChanging(value);
					this.SendPropertyChanging();
					this._Sonda = value;
					this.SendPropertyChanged("Sonda");
					this.OnSondaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HospSuresi", DbType="Int")]
		public System.Nullable<int> HospSuresi
		{
			get
			{
				return this._HospSuresi;
			}
			set
			{
				if ((this._HospSuresi != value))
				{
					this.OnHospSuresiChanging(value);
					this.SendPropertyChanging();
					this._HospSuresi = value;
					this.SendPropertyChanged("HospSuresi");
					this.OnHospSuresiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PreopKreatin", DbType="Decimal(6,0)")]
		public System.Nullable<decimal> PreopKreatin
		{
			get
			{
				return this._PreopKreatin;
			}
			set
			{
				if ((this._PreopKreatin != value))
				{
					this.OnPreopKreatinChanging(value);
					this.SendPropertyChanging();
					this._PreopKreatin = value;
					this.SendPropertyChanged("PreopKreatin");
					this.OnPreopKreatinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostopKreatin", DbType="Decimal(6,0)")]
		public System.Nullable<decimal> PostopKreatin
		{
			get
			{
				return this._PostopKreatin;
			}
			set
			{
				if ((this._PostopKreatin != value))
				{
					this.OnPostopKreatinChanging(value);
					this.SendPropertyChanging();
					this._PostopKreatin = value;
					this.SendPropertyChanged("PostopKreatin");
					this.OnPostopKreatinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PreopHct", DbType="Decimal(6,0)")]
		public System.Nullable<decimal> PreopHct
		{
			get
			{
				return this._PreopHct;
			}
			set
			{
				if ((this._PreopHct != value))
				{
					this.OnPreopHctChanging(value);
					this.SendPropertyChanging();
					this._PreopHct = value;
					this.SendPropertyChanged("PreopHct");
					this.OnPreopHctChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostopHct", DbType="Decimal(6,0)")]
		public System.Nullable<decimal> PostopHct
		{
			get
			{
				return this._PostopHct;
			}
			set
			{
				if ((this._PostopHct != value))
				{
					this.OnPostopHctChanging(value);
					this.SendPropertyChanging();
					this._PostopHct = value;
					this.SendPropertyChanged("PostopHct");
					this.OnPostopHctChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PreopHb", DbType="Decimal(6,0)")]
		public System.Nullable<decimal> PreopHb
		{
			get
			{
				return this._PreopHb;
			}
			set
			{
				if ((this._PreopHb != value))
				{
					this.OnPreopHbChanging(value);
					this.SendPropertyChanging();
					this._PreopHb = value;
					this.SendPropertyChanged("PreopHb");
					this.OnPreopHbChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostopHb", DbType="Decimal(6,0)")]
		public System.Nullable<decimal> PostopHb
		{
			get
			{
				return this._PostopHb;
			}
			set
			{
				if ((this._PostopHb != value))
				{
					this.OnPostopHbChanging(value);
					this.SendPropertyChanging();
					this._PostopHb = value;
					this.SendPropertyChanged("PostopHb");
					this.OnPostopHbChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Takip", DbType="NVarChar(50)")]
		public string Takip
		{
			get
			{
				return this._Takip;
			}
			set
			{
				if ((this._Takip != value))
				{
					this.OnTakipChanging(value);
					this.SendPropertyChanging();
					this._Takip = value;
					this.SendPropertyChanged("Takip");
					this.OnTakipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tel", DbType="NVarChar(50)")]
		public string Tel
		{
			get
			{
				return this._Tel;
			}
			set
			{
				if ((this._Tel != value))
				{
					this.OnTelChanging(value);
					this.SendPropertyChanging();
					this._Tel = value;
					this.SendPropertyChanged("Tel");
					this.OnTelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostopGecKomp", DbType="NVarChar(50)")]
		public string PostopGecKomp
		{
			get
			{
				return this._PostopGecKomp;
			}
			set
			{
				if ((this._PostopGecKomp != value))
				{
					this.OnPostopGecKompChanging(value);
					this.SendPropertyChanging();
					this._PostopGecKomp = value;
					this.SendPropertyChanged("PostopGecKomp");
					this.OnPostopGecKompChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KompClavien", DbType="NVarChar(10)")]
		public string KompClavien
		{
			get
			{
				return this._KompClavien;
			}
			set
			{
				if ((this._KompClavien != value))
				{
					this.OnKompClavienChanging(value);
					this.SendPropertyChanging();
					this._KompClavien = value;
					this.SendPropertyChanged("KompClavien");
					this.OnKompClavienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblHastaBilgileri_tblPosOperatifOzellikler", Storage="_tblHastaBilgileri", ThisKey="hastaID", OtherKey="hastaID", IsForeignKey=true)]
		public tblHastaBilgileri tblHastaBilgileri
		{
			get
			{
				return this._tblHastaBilgileri.Entity;
			}
			set
			{
				tblHastaBilgileri previousValue = this._tblHastaBilgileri.Entity;
				if (((previousValue != value) 
							|| (this._tblHastaBilgileri.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblHastaBilgileri.Entity = null;
						previousValue.tblPosOperatifOzelliklers.Remove(this);
					}
					this._tblHastaBilgileri.Entity = value;
					if ((value != null))
					{
						value.tblPosOperatifOzelliklers.Add(this);
						this._hastaID = value.hastaID;
					}
					else
					{
						this._hastaID = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblHastaBilgileri");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblPatolojikVeriler")]
	public partial class tblPatolojikVeriler : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _hastaID;
		
		private System.Nullable<int> _hastaNo;
		
		private string _Patoloji;
		
		private string _AltGrup;
		
		private System.Nullable<int> _FurhmanGrade;
		
		private string _PatolojikEvre;
		
		private string _CerrahiSinir;
		
		private EntityRef<tblHastaBilgileri> _tblHastaBilgileri;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnhastaIDChanging(System.Nullable<int> value);
    partial void OnhastaIDChanged();
    partial void OnhastaNoChanging(System.Nullable<int> value);
    partial void OnhastaNoChanged();
    partial void OnPatolojiChanging(string value);
    partial void OnPatolojiChanged();
    partial void OnAltGrupChanging(string value);
    partial void OnAltGrupChanged();
    partial void OnFurhmanGradeChanging(System.Nullable<int> value);
    partial void OnFurhmanGradeChanged();
    partial void OnPatolojikEvreChanging(string value);
    partial void OnPatolojikEvreChanged();
    partial void OnCerrahiSinirChanging(string value);
    partial void OnCerrahiSinirChanged();
    #endregion
		
		public tblPatolojikVeriler()
		{
			this._tblHastaBilgileri = default(EntityRef<tblHastaBilgileri>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hastaID", DbType="Int")]
		public System.Nullable<int> hastaID
		{
			get
			{
				return this._hastaID;
			}
			set
			{
				if ((this._hastaID != value))
				{
					if (this._tblHastaBilgileri.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnhastaIDChanging(value);
					this.SendPropertyChanging();
					this._hastaID = value;
					this.SendPropertyChanged("hastaID");
					this.OnhastaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hastaNo", DbType="Int")]
		public System.Nullable<int> hastaNo
		{
			get
			{
				return this._hastaNo;
			}
			set
			{
				if ((this._hastaNo != value))
				{
					this.OnhastaNoChanging(value);
					this.SendPropertyChanging();
					this._hastaNo = value;
					this.SendPropertyChanged("hastaNo");
					this.OnhastaNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Patoloji", DbType="NVarChar(50)")]
		public string Patoloji
		{
			get
			{
				return this._Patoloji;
			}
			set
			{
				if ((this._Patoloji != value))
				{
					this.OnPatolojiChanging(value);
					this.SendPropertyChanging();
					this._Patoloji = value;
					this.SendPropertyChanged("Patoloji");
					this.OnPatolojiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AltGrup", DbType="NVarChar(70)")]
		public string AltGrup
		{
			get
			{
				return this._AltGrup;
			}
			set
			{
				if ((this._AltGrup != value))
				{
					this.OnAltGrupChanging(value);
					this.SendPropertyChanging();
					this._AltGrup = value;
					this.SendPropertyChanged("AltGrup");
					this.OnAltGrupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FurhmanGrade", DbType="Int")]
		public System.Nullable<int> FurhmanGrade
		{
			get
			{
				return this._FurhmanGrade;
			}
			set
			{
				if ((this._FurhmanGrade != value))
				{
					this.OnFurhmanGradeChanging(value);
					this.SendPropertyChanging();
					this._FurhmanGrade = value;
					this.SendPropertyChanged("FurhmanGrade");
					this.OnFurhmanGradeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatolojikEvre", DbType="NVarChar(10)")]
		public string PatolojikEvre
		{
			get
			{
				return this._PatolojikEvre;
			}
			set
			{
				if ((this._PatolojikEvre != value))
				{
					this.OnPatolojikEvreChanging(value);
					this.SendPropertyChanging();
					this._PatolojikEvre = value;
					this.SendPropertyChanged("PatolojikEvre");
					this.OnPatolojikEvreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CerrahiSinir", DbType="NVarChar(10)")]
		public string CerrahiSinir
		{
			get
			{
				return this._CerrahiSinir;
			}
			set
			{
				if ((this._CerrahiSinir != value))
				{
					this.OnCerrahiSinirChanging(value);
					this.SendPropertyChanging();
					this._CerrahiSinir = value;
					this.SendPropertyChanged("CerrahiSinir");
					this.OnCerrahiSinirChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblHastaBilgileri_tblPatolojikVeriler", Storage="_tblHastaBilgileri", ThisKey="hastaID", OtherKey="hastaID", IsForeignKey=true)]
		public tblHastaBilgileri tblHastaBilgileri
		{
			get
			{
				return this._tblHastaBilgileri.Entity;
			}
			set
			{
				tblHastaBilgileri previousValue = this._tblHastaBilgileri.Entity;
				if (((previousValue != value) 
							|| (this._tblHastaBilgileri.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblHastaBilgileri.Entity = null;
						previousValue.tblPatolojikVerilers.Remove(this);
					}
					this._tblHastaBilgileri.Entity = value;
					if ((value != null))
					{
						value.tblPatolojikVerilers.Add(this);
						this._hastaID = value.hastaID;
					}
					else
					{
						this._hastaID = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblHastaBilgileri");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblOpTuru")]
	public partial class tblOpTuru : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _OpTuru;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnOpTuruChanging(string value);
    partial void OnOpTuruChanged();
    #endregion
		
		public tblOpTuru()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OpTuru", DbType="NVarChar(50)")]
		public string OpTuru
		{
			get
			{
				return this._OpTuru;
			}
			set
			{
				if ((this._OpTuru != value))
				{
					this.OnOpTuruChanging(value);
					this.SendPropertyChanging();
					this._OpTuru = value;
					this.SendPropertyChanged("OpTuru");
					this.OnOpTuruChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblOperatifOzellikler")]
	public partial class tblOperatifOzellikler : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _hastaID;
		
		private System.Nullable<int> _HastaNo;
		
		private string _PksAciklama;
		
		private string _Sik;
		
		private string _CoOperasyon;
		
		private System.Nullable<int> _Iskemi;
		
		private System.Nullable<int> _PortSayisi;
		
		private string _YardımYnt;
		
		private System.Nullable<int> _Sure;
		
		private System.Nullable<int> _Dren;
		
		private System.Nullable<int> _Kanama;
		
		private string _Piyes;
		
		private EntityRef<tblHastaBilgileri> _tblHastaBilgileri;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnhastaIDChanging(System.Nullable<int> value);
    partial void OnhastaIDChanged();
    partial void OnHastaNoChanging(System.Nullable<int> value);
    partial void OnHastaNoChanged();
    partial void OnPksAciklamaChanging(string value);
    partial void OnPksAciklamaChanged();
    partial void OnSikChanging(string value);
    partial void OnSikChanged();
    partial void OnCoOperasyonChanging(string value);
    partial void OnCoOperasyonChanged();
    partial void OnIskemiChanging(System.Nullable<int> value);
    partial void OnIskemiChanged();
    partial void OnPortSayisiChanging(System.Nullable<int> value);
    partial void OnPortSayisiChanged();
    partial void OnYardımYntChanging(string value);
    partial void OnYardımYntChanged();
    partial void OnSureChanging(System.Nullable<int> value);
    partial void OnSureChanged();
    partial void OnDrenChanging(System.Nullable<int> value);
    partial void OnDrenChanged();
    partial void OnKanamaChanging(System.Nullable<int> value);
    partial void OnKanamaChanged();
    partial void OnPiyesChanging(string value);
    partial void OnPiyesChanged();
    #endregion
		
		public tblOperatifOzellikler()
		{
			this._tblHastaBilgileri = default(EntityRef<tblHastaBilgileri>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hastaID", DbType="Int")]
		public System.Nullable<int> hastaID
		{
			get
			{
				return this._hastaID;
			}
			set
			{
				if ((this._hastaID != value))
				{
					if (this._tblHastaBilgileri.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnhastaIDChanging(value);
					this.SendPropertyChanging();
					this._hastaID = value;
					this.SendPropertyChanged("hastaID");
					this.OnhastaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HastaNo", DbType="Int")]
		public System.Nullable<int> HastaNo
		{
			get
			{
				return this._HastaNo;
			}
			set
			{
				if ((this._HastaNo != value))
				{
					this.OnHastaNoChanging(value);
					this.SendPropertyChanging();
					this._HastaNo = value;
					this.SendPropertyChanged("HastaNo");
					this.OnHastaNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PksAciklama", DbType="NVarChar(10)")]
		public string PksAciklama
		{
			get
			{
				return this._PksAciklama;
			}
			set
			{
				if ((this._PksAciklama != value))
				{
					this.OnPksAciklamaChanging(value);
					this.SendPropertyChanging();
					this._PksAciklama = value;
					this.SendPropertyChanged("PksAciklama");
					this.OnPksAciklamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sik", DbType="NVarChar(30)")]
		public string Sik
		{
			get
			{
				return this._Sik;
			}
			set
			{
				if ((this._Sik != value))
				{
					this.OnSikChanging(value);
					this.SendPropertyChanging();
					this._Sik = value;
					this.SendPropertyChanged("Sik");
					this.OnSikChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CoOperasyon", DbType="NVarChar(50)")]
		public string CoOperasyon
		{
			get
			{
				return this._CoOperasyon;
			}
			set
			{
				if ((this._CoOperasyon != value))
				{
					this.OnCoOperasyonChanging(value);
					this.SendPropertyChanging();
					this._CoOperasyon = value;
					this.SendPropertyChanged("CoOperasyon");
					this.OnCoOperasyonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Iskemi", DbType="Int")]
		public System.Nullable<int> Iskemi
		{
			get
			{
				return this._Iskemi;
			}
			set
			{
				if ((this._Iskemi != value))
				{
					this.OnIskemiChanging(value);
					this.SendPropertyChanging();
					this._Iskemi = value;
					this.SendPropertyChanged("Iskemi");
					this.OnIskemiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PortSayisi", DbType="Int")]
		public System.Nullable<int> PortSayisi
		{
			get
			{
				return this._PortSayisi;
			}
			set
			{
				if ((this._PortSayisi != value))
				{
					this.OnPortSayisiChanging(value);
					this.SendPropertyChanging();
					this._PortSayisi = value;
					this.SendPropertyChanged("PortSayisi");
					this.OnPortSayisiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YardımYnt", DbType="NVarChar(50)")]
		public string YardımYnt
		{
			get
			{
				return this._YardımYnt;
			}
			set
			{
				if ((this._YardımYnt != value))
				{
					this.OnYardımYntChanging(value);
					this.SendPropertyChanging();
					this._YardımYnt = value;
					this.SendPropertyChanged("YardımYnt");
					this.OnYardımYntChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sure", DbType="Int")]
		public System.Nullable<int> Sure
		{
			get
			{
				return this._Sure;
			}
			set
			{
				if ((this._Sure != value))
				{
					this.OnSureChanging(value);
					this.SendPropertyChanging();
					this._Sure = value;
					this.SendPropertyChanged("Sure");
					this.OnSureChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dren", DbType="Int")]
		public System.Nullable<int> Dren
		{
			get
			{
				return this._Dren;
			}
			set
			{
				if ((this._Dren != value))
				{
					this.OnDrenChanging(value);
					this.SendPropertyChanging();
					this._Dren = value;
					this.SendPropertyChanged("Dren");
					this.OnDrenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kanama", DbType="Int")]
		public System.Nullable<int> Kanama
		{
			get
			{
				return this._Kanama;
			}
			set
			{
				if ((this._Kanama != value))
				{
					this.OnKanamaChanging(value);
					this.SendPropertyChanging();
					this._Kanama = value;
					this.SendPropertyChanged("Kanama");
					this.OnKanamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Piyes", DbType="NVarChar(50)")]
		public string Piyes
		{
			get
			{
				return this._Piyes;
			}
			set
			{
				if ((this._Piyes != value))
				{
					this.OnPiyesChanging(value);
					this.SendPropertyChanging();
					this._Piyes = value;
					this.SendPropertyChanged("Piyes");
					this.OnPiyesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblHastaBilgileri_tblOperatifOzellikler", Storage="_tblHastaBilgileri", ThisKey="hastaID", OtherKey="hastaID", IsForeignKey=true)]
		public tblHastaBilgileri tblHastaBilgileri
		{
			get
			{
				return this._tblHastaBilgileri.Entity;
			}
			set
			{
				tblHastaBilgileri previousValue = this._tblHastaBilgileri.Entity;
				if (((previousValue != value) 
							|| (this._tblHastaBilgileri.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblHastaBilgileri.Entity = null;
						previousValue.tblOperatifOzelliklers.Remove(this);
					}
					this._tblHastaBilgileri.Entity = value;
					if ((value != null))
					{
						value.tblOperatifOzelliklers.Add(this);
						this._hastaID = value.hastaID;
					}
					else
					{
						this._hastaID = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblHastaBilgileri");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblKoMorbidite")]
	public partial class tblKoMorbidite : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _KoMorbidite;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnKoMorbiditeChanging(string value);
    partial void OnKoMorbiditeChanged();
    #endregion
		
		public tblKoMorbidite()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KoMorbidite", DbType="NVarChar(50)")]
		public string KoMorbidite
		{
			get
			{
				return this._KoMorbidite;
			}
			set
			{
				if ((this._KoMorbidite != value))
				{
					this.OnKoMorbiditeChanging(value);
					this.SendPropertyChanging();
					this._KoMorbidite = value;
					this.SendPropertyChanged("KoMorbidite");
					this.OnKoMorbiditeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblDR")]
	public partial class tblDR : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _DR;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnDRChanging(string value);
    partial void OnDRChanged();
    #endregion
		
		public tblDR()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DR", DbType="NVarChar(50)")]
		public string DR
		{
			get
			{
				return this._DR;
			}
			set
			{
				if ((this._DR != value))
				{
					this.OnDRChanging(value);
					this.SendPropertyChanging();
					this._DR = value;
					this.SendPropertyChanged("DR");
					this.OnDRChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblHastaBilgileri")]
	public partial class tblHastaBilgileri : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _hastaID;
		
		private System.Nullable<int> _HastaNo;
		
		private string _Ad;
		
		private string _Soyad;
		
		private string _Protokol;
		
		private System.Nullable<System.DateTime> _OpTarihi;
		
		private string _OpTuru;
		
		private System.Nullable<int> _Takip;
		
		private System.Nullable<int> _Anah;
		
		private EntitySet<tblTakipVerileri> _tblTakipVerileris;
		
		private EntitySet<tblPosOperatifOzellikler> _tblPosOperatifOzelliklers;
		
		private EntitySet<tblPatolojikVeriler> _tblPatolojikVerilers;
		
		private EntitySet<tblOperatifOzellikler> _tblOperatifOzelliklers;
		
		private EntitySet<tblDemografikOzellikler> _tblDemografikOzelliklers;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnhastaIDChanging(int value);
    partial void OnhastaIDChanged();
    partial void OnHastaNoChanging(System.Nullable<int> value);
    partial void OnHastaNoChanged();
    partial void OnAdChanging(string value);
    partial void OnAdChanged();
    partial void OnSoyadChanging(string value);
    partial void OnSoyadChanged();
    partial void OnProtokolChanging(string value);
    partial void OnProtokolChanged();
    partial void OnOpTarihiChanging(System.Nullable<System.DateTime> value);
    partial void OnOpTarihiChanged();
    partial void OnOpTuruChanging(string value);
    partial void OnOpTuruChanged();
    partial void OnTakipChanging(System.Nullable<int> value);
    partial void OnTakipChanged();
    partial void OnAnahChanging(System.Nullable<int> value);
    partial void OnAnahChanged();
    #endregion
		
		public tblHastaBilgileri()
		{
			this._tblTakipVerileris = new EntitySet<tblTakipVerileri>(new Action<tblTakipVerileri>(this.attach_tblTakipVerileris), new Action<tblTakipVerileri>(this.detach_tblTakipVerileris));
			this._tblPosOperatifOzelliklers = new EntitySet<tblPosOperatifOzellikler>(new Action<tblPosOperatifOzellikler>(this.attach_tblPosOperatifOzelliklers), new Action<tblPosOperatifOzellikler>(this.detach_tblPosOperatifOzelliklers));
			this._tblPatolojikVerilers = new EntitySet<tblPatolojikVeriler>(new Action<tblPatolojikVeriler>(this.attach_tblPatolojikVerilers), new Action<tblPatolojikVeriler>(this.detach_tblPatolojikVerilers));
			this._tblOperatifOzelliklers = new EntitySet<tblOperatifOzellikler>(new Action<tblOperatifOzellikler>(this.attach_tblOperatifOzelliklers), new Action<tblOperatifOzellikler>(this.detach_tblOperatifOzelliklers));
			this._tblDemografikOzelliklers = new EntitySet<tblDemografikOzellikler>(new Action<tblDemografikOzellikler>(this.attach_tblDemografikOzelliklers), new Action<tblDemografikOzellikler>(this.detach_tblDemografikOzelliklers));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hastaID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int hastaID
		{
			get
			{
				return this._hastaID;
			}
			set
			{
				if ((this._hastaID != value))
				{
					this.OnhastaIDChanging(value);
					this.SendPropertyChanging();
					this._hastaID = value;
					this.SendPropertyChanged("hastaID");
					this.OnhastaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HastaNo", DbType="Int")]
		public System.Nullable<int> HastaNo
		{
			get
			{
				return this._HastaNo;
			}
			set
			{
				if ((this._HastaNo != value))
				{
					this.OnHastaNoChanging(value);
					this.SendPropertyChanging();
					this._HastaNo = value;
					this.SendPropertyChanged("HastaNo");
					this.OnHastaNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ad", DbType="NVarChar(50)")]
		public string Ad
		{
			get
			{
				return this._Ad;
			}
			set
			{
				if ((this._Ad != value))
				{
					this.OnAdChanging(value);
					this.SendPropertyChanging();
					this._Ad = value;
					this.SendPropertyChanged("Ad");
					this.OnAdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Soyad", DbType="NVarChar(50)")]
		public string Soyad
		{
			get
			{
				return this._Soyad;
			}
			set
			{
				if ((this._Soyad != value))
				{
					this.OnSoyadChanging(value);
					this.SendPropertyChanging();
					this._Soyad = value;
					this.SendPropertyChanged("Soyad");
					this.OnSoyadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Protokol", DbType="NVarChar(20)")]
		public string Protokol
		{
			get
			{
				return this._Protokol;
			}
			set
			{
				if ((this._Protokol != value))
				{
					this.OnProtokolChanging(value);
					this.SendPropertyChanging();
					this._Protokol = value;
					this.SendPropertyChanged("Protokol");
					this.OnProtokolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OpTarihi", DbType="Date")]
		public System.Nullable<System.DateTime> OpTarihi
		{
			get
			{
				return this._OpTarihi;
			}
			set
			{
				if ((this._OpTarihi != value))
				{
					this.OnOpTarihiChanging(value);
					this.SendPropertyChanging();
					this._OpTarihi = value;
					this.SendPropertyChanged("OpTarihi");
					this.OnOpTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OpTuru", DbType="NVarChar(50)")]
		public string OpTuru
		{
			get
			{
				return this._OpTuru;
			}
			set
			{
				if ((this._OpTuru != value))
				{
					this.OnOpTuruChanging(value);
					this.SendPropertyChanging();
					this._OpTuru = value;
					this.SendPropertyChanged("OpTuru");
					this.OnOpTuruChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Takip", DbType="Int")]
		public System.Nullable<int> Takip
		{
			get
			{
				return this._Takip;
			}
			set
			{
				if ((this._Takip != value))
				{
					this.OnTakipChanging(value);
					this.SendPropertyChanging();
					this._Takip = value;
					this.SendPropertyChanged("Takip");
					this.OnTakipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Anah", DbType="Int")]
		public System.Nullable<int> Anah
		{
			get
			{
				return this._Anah;
			}
			set
			{
				if ((this._Anah != value))
				{
					this.OnAnahChanging(value);
					this.SendPropertyChanging();
					this._Anah = value;
					this.SendPropertyChanged("Anah");
					this.OnAnahChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblHastaBilgileri_tblTakipVerileri", Storage="_tblTakipVerileris", ThisKey="hastaID", OtherKey="hastaID")]
		public EntitySet<tblTakipVerileri> tblTakipVerileris
		{
			get
			{
				return this._tblTakipVerileris;
			}
			set
			{
				this._tblTakipVerileris.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblHastaBilgileri_tblPosOperatifOzellikler", Storage="_tblPosOperatifOzelliklers", ThisKey="hastaID", OtherKey="hastaID")]
		public EntitySet<tblPosOperatifOzellikler> tblPosOperatifOzelliklers
		{
			get
			{
				return this._tblPosOperatifOzelliklers;
			}
			set
			{
				this._tblPosOperatifOzelliklers.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblHastaBilgileri_tblPatolojikVeriler", Storage="_tblPatolojikVerilers", ThisKey="hastaID", OtherKey="hastaID")]
		public EntitySet<tblPatolojikVeriler> tblPatolojikVerilers
		{
			get
			{
				return this._tblPatolojikVerilers;
			}
			set
			{
				this._tblPatolojikVerilers.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblHastaBilgileri_tblOperatifOzellikler", Storage="_tblOperatifOzelliklers", ThisKey="hastaID", OtherKey="hastaID")]
		public EntitySet<tblOperatifOzellikler> tblOperatifOzelliklers
		{
			get
			{
				return this._tblOperatifOzelliklers;
			}
			set
			{
				this._tblOperatifOzelliklers.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblHastaBilgileri_tblDemografikOzellikler", Storage="_tblDemografikOzelliklers", ThisKey="hastaID", OtherKey="hastaID")]
		public EntitySet<tblDemografikOzellikler> tblDemografikOzelliklers
		{
			get
			{
				return this._tblDemografikOzelliklers;
			}
			set
			{
				this._tblDemografikOzelliklers.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblTakipVerileris(tblTakipVerileri entity)
		{
			this.SendPropertyChanging();
			entity.tblHastaBilgileri = this;
		}
		
		private void detach_tblTakipVerileris(tblTakipVerileri entity)
		{
			this.SendPropertyChanging();
			entity.tblHastaBilgileri = null;
		}
		
		private void attach_tblPosOperatifOzelliklers(tblPosOperatifOzellikler entity)
		{
			this.SendPropertyChanging();
			entity.tblHastaBilgileri = this;
		}
		
		private void detach_tblPosOperatifOzelliklers(tblPosOperatifOzellikler entity)
		{
			this.SendPropertyChanging();
			entity.tblHastaBilgileri = null;
		}
		
		private void attach_tblPatolojikVerilers(tblPatolojikVeriler entity)
		{
			this.SendPropertyChanging();
			entity.tblHastaBilgileri = this;
		}
		
		private void detach_tblPatolojikVerilers(tblPatolojikVeriler entity)
		{
			this.SendPropertyChanging();
			entity.tblHastaBilgileri = null;
		}
		
		private void attach_tblOperatifOzelliklers(tblOperatifOzellikler entity)
		{
			this.SendPropertyChanging();
			entity.tblHastaBilgileri = this;
		}
		
		private void detach_tblOperatifOzelliklers(tblOperatifOzellikler entity)
		{
			this.SendPropertyChanging();
			entity.tblHastaBilgileri = null;
		}
		
		private void attach_tblDemografikOzelliklers(tblDemografikOzellikler entity)
		{
			this.SendPropertyChanging();
			entity.tblHastaBilgileri = this;
		}
		
		private void detach_tblDemografikOzelliklers(tblDemografikOzellikler entity)
		{
			this.SendPropertyChanging();
			entity.tblHastaBilgileri = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblDemografikOzellikler")]
	public partial class tblDemografikOzellikler : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _hastaID;
		
		private System.Nullable<int> _HastaNo;
		
		private System.Nullable<int> _Yas;
		
		private System.Nullable<decimal> _Boy;
		
		private System.Nullable<decimal> _Kilo;
		
		private System.Nullable<decimal> _Bmi;
		
		private System.Nullable<int> _Asa;
		
		private string _Dr;
		
		private string _Cins;
		
		private string _Taraf;
		
		private string _Lokalizasyon;
		
		private string _Boyut;
		
		private string _Ko_Morbidite;
		
		private EntityRef<tblHastaBilgileri> _tblHastaBilgileri;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnhastaIDChanging(System.Nullable<int> value);
    partial void OnhastaIDChanged();
    partial void OnHastaNoChanging(System.Nullable<int> value);
    partial void OnHastaNoChanged();
    partial void OnYasChanging(System.Nullable<int> value);
    partial void OnYasChanged();
    partial void OnBoyChanging(System.Nullable<decimal> value);
    partial void OnBoyChanged();
    partial void OnKiloChanging(System.Nullable<decimal> value);
    partial void OnKiloChanged();
    partial void OnBmiChanging(System.Nullable<decimal> value);
    partial void OnBmiChanged();
    partial void OnAsaChanging(System.Nullable<int> value);
    partial void OnAsaChanged();
    partial void OnDrChanging(string value);
    partial void OnDrChanged();
    partial void OnCinsChanging(string value);
    partial void OnCinsChanged();
    partial void OnTarafChanging(string value);
    partial void OnTarafChanged();
    partial void OnLokalizasyonChanging(string value);
    partial void OnLokalizasyonChanged();
    partial void OnBoyutChanging(string value);
    partial void OnBoyutChanged();
    partial void OnKo_MorbiditeChanging(string value);
    partial void OnKo_MorbiditeChanged();
    #endregion
		
		public tblDemografikOzellikler()
		{
			this._tblHastaBilgileri = default(EntityRef<tblHastaBilgileri>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hastaID", DbType="Int")]
		public System.Nullable<int> hastaID
		{
			get
			{
				return this._hastaID;
			}
			set
			{
				if ((this._hastaID != value))
				{
					if (this._tblHastaBilgileri.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnhastaIDChanging(value);
					this.SendPropertyChanging();
					this._hastaID = value;
					this.SendPropertyChanged("hastaID");
					this.OnhastaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HastaNo", DbType="Int")]
		public System.Nullable<int> HastaNo
		{
			get
			{
				return this._HastaNo;
			}
			set
			{
				if ((this._HastaNo != value))
				{
					this.OnHastaNoChanging(value);
					this.SendPropertyChanging();
					this._HastaNo = value;
					this.SendPropertyChanged("HastaNo");
					this.OnHastaNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Yas", DbType="Int")]
		public System.Nullable<int> Yas
		{
			get
			{
				return this._Yas;
			}
			set
			{
				if ((this._Yas != value))
				{
					this.OnYasChanging(value);
					this.SendPropertyChanging();
					this._Yas = value;
					this.SendPropertyChanged("Yas");
					this.OnYasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Boy", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> Boy
		{
			get
			{
				return this._Boy;
			}
			set
			{
				if ((this._Boy != value))
				{
					this.OnBoyChanging(value);
					this.SendPropertyChanging();
					this._Boy = value;
					this.SendPropertyChanged("Boy");
					this.OnBoyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kilo", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> Kilo
		{
			get
			{
				return this._Kilo;
			}
			set
			{
				if ((this._Kilo != value))
				{
					this.OnKiloChanging(value);
					this.SendPropertyChanging();
					this._Kilo = value;
					this.SendPropertyChanged("Kilo");
					this.OnKiloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bmi", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> Bmi
		{
			get
			{
				return this._Bmi;
			}
			set
			{
				if ((this._Bmi != value))
				{
					this.OnBmiChanging(value);
					this.SendPropertyChanging();
					this._Bmi = value;
					this.SendPropertyChanged("Bmi");
					this.OnBmiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Asa", DbType="Int")]
		public System.Nullable<int> Asa
		{
			get
			{
				return this._Asa;
			}
			set
			{
				if ((this._Asa != value))
				{
					this.OnAsaChanging(value);
					this.SendPropertyChanging();
					this._Asa = value;
					this.SendPropertyChanged("Asa");
					this.OnAsaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dr", DbType="NVarChar(50)")]
		public string Dr
		{
			get
			{
				return this._Dr;
			}
			set
			{
				if ((this._Dr != value))
				{
					this.OnDrChanging(value);
					this.SendPropertyChanging();
					this._Dr = value;
					this.SendPropertyChanged("Dr");
					this.OnDrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cins", DbType="NVarChar(10)")]
		public string Cins
		{
			get
			{
				return this._Cins;
			}
			set
			{
				if ((this._Cins != value))
				{
					this.OnCinsChanging(value);
					this.SendPropertyChanging();
					this._Cins = value;
					this.SendPropertyChanged("Cins");
					this.OnCinsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Taraf", DbType="NVarChar(10)")]
		public string Taraf
		{
			get
			{
				return this._Taraf;
			}
			set
			{
				if ((this._Taraf != value))
				{
					this.OnTarafChanging(value);
					this.SendPropertyChanging();
					this._Taraf = value;
					this.SendPropertyChanged("Taraf");
					this.OnTarafChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lokalizasyon", DbType="NVarChar(70)")]
		public string Lokalizasyon
		{
			get
			{
				return this._Lokalizasyon;
			}
			set
			{
				if ((this._Lokalizasyon != value))
				{
					this.OnLokalizasyonChanging(value);
					this.SendPropertyChanging();
					this._Lokalizasyon = value;
					this.SendPropertyChanged("Lokalizasyon");
					this.OnLokalizasyonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Boyut", DbType="NVarChar(50)")]
		public string Boyut
		{
			get
			{
				return this._Boyut;
			}
			set
			{
				if ((this._Boyut != value))
				{
					this.OnBoyutChanging(value);
					this.SendPropertyChanging();
					this._Boyut = value;
					this.SendPropertyChanged("Boyut");
					this.OnBoyutChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Ko-Morbidite]", Storage="_Ko_Morbidite", DbType="NVarChar(30)")]
		public string Ko_Morbidite
		{
			get
			{
				return this._Ko_Morbidite;
			}
			set
			{
				if ((this._Ko_Morbidite != value))
				{
					this.OnKo_MorbiditeChanging(value);
					this.SendPropertyChanging();
					this._Ko_Morbidite = value;
					this.SendPropertyChanged("Ko_Morbidite");
					this.OnKo_MorbiditeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblHastaBilgileri_tblDemografikOzellikler", Storage="_tblHastaBilgileri", ThisKey="hastaID", OtherKey="hastaID", IsForeignKey=true)]
		public tblHastaBilgileri tblHastaBilgileri
		{
			get
			{
				return this._tblHastaBilgileri.Entity;
			}
			set
			{
				tblHastaBilgileri previousValue = this._tblHastaBilgileri.Entity;
				if (((previousValue != value) 
							|| (this._tblHastaBilgileri.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblHastaBilgileri.Entity = null;
						previousValue.tblDemografikOzelliklers.Remove(this);
					}
					this._tblHastaBilgileri.Entity = value;
					if ((value != null))
					{
						value.tblDemografikOzelliklers.Add(this);
						this._hastaID = value.hastaID;
					}
					else
					{
						this._hastaID = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblHastaBilgileri");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
